open Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module T = Types_generated

module Functions (F : FOREIGN) = struct
  open F
  open T.Base_types

  module Device = struct
    let t = ptr T.Device.t

    let create = foreign "gbm_create_device" @@ fd @-> returning (ptr_opt T.Device.t)
    let destroy = foreign "gbm_device_destroy" @@ t @-> returning void

    let get_format_modifier_plane_count = foreign "gbm_device_get_format_modifier_plane_count" @@
      t @-> drm_format @-> modifier @-> returning int

    let get_backend_name = foreign "gbm_device_get_backend_name" @@ t @-> returning string
    let is_format_supported = foreign "gbm_device_is_format_supported" @@ t @-> drm_format @-> T.Bo_flags.t @-> returning bool_int
  end

  module Bo = struct
    let t = ptr T.Bo.t

    let create =
      foreign "gbm_bo_create" @@
      ptr T.Device.t @->
      int_uint32_t @->
      int_uint32_t @->
      drm_format @->
      uint32_t @->
      returning (ptr_opt T.Bo.t)

    let create_with_modifiers2 =
      foreign "gbm_bo_create_with_modifiers2" @@
      ptr T.Device.t @->
      int_uint32_t @->
      int_uint32_t @->
      drm_format @-> ptr modifier @-> int_uint @->
      uint32_t @->
      returning (ptr_opt T.Bo.t)

    let import =
      foreign "gbm_bo_import" @@
      ptr T.Device.t @->
      uint32_t @->
      ptr void @->
      uint32_t @->
      returning (ptr_opt T.Bo.t)

    let destroy = foreign "gbm_bo_destroy" @@ t @-> returning void

    let get_offset = foreign "gbm_bo_get_offset" @@ t @-> int @-> returning int_uint32_t
    let get_stride_for_plane = foreign "gbm_bo_get_stride_for_plane" @@ t @-> int @-> returning int_uint32_t
    let get_fd = foreign "gbm_bo_get_fd" @@ t @-> returning fd
    let get_fd_for_plane = foreign "gbm_bo_get_fd_for_plane" @@ t @-> int @-> returning fd
    let get_plane_count = foreign "gbm_bo_get_plane_count" @@ t @-> returning int
    let get_handle = foreign "gbm_bo_get_handle" @@ t @-> returning T.Bo_handle.t
    let get_handle_for_plane = foreign "gbm_bo_get_handle_for_plane" @@ t @-> int @-> returning T.Bo_handle.t
    let get_modifier = foreign "gbm_bo_get_modifier" @@ t @-> returning modifier
    let get_bpp = foreign "gbm_bo_get_bpp" @@ t @-> returning int_uint32_t

    let get_width = foreign "gbm_bo_get_width" @@ t @-> returning int_uint32_t
    let get_height = foreign "gbm_bo_get_height" @@ t @-> returning int_uint32_t

    type map_data = unit Ctypes.ptr
    let map_data = ptr void

    let map = foreign "gbm_bo_map" @@
      t @->
      int_uint32_t @-> int_uint32_t @->
      int_uint32_t @-> int_uint32_t @->
      uint32_t @-> ptr int_uint32_t @-> ptr map_data @->
      returning (ptr_opt void)

    let unmap = foreign "gbm_bo_unmap" @@ t @-> map_data @-> returning void
  end
end
