open Ctypes

let int_of_unix (fd : Unix.file_descr) : int = Obj.magic fd
let unix_of_int (fd : int) : Unix.file_descr = assert (fd >= 0); Obj.magic fd

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module T = Types_generated

module Functions (F : FOREIGN) = struct
  open F

  let fd = view ~read:unix_of_int ~write:int_of_unix int

  let drm_format = view uint32_t ~read:Drm.Fourcc.of_uint32 ~write:Drm.Fourcc.to_uint32
  let modifier = view uint64_t ~read:Drm.Modifier.of_uint64 ~write:Drm.Modifier.to_uint64

  let int_uint32_t = view ~read:Unsigned.UInt32.to_int ~write:Unsigned.UInt32.of_int uint32_t
  let int_uint = view ~read:Unsigned.UInt.to_int ~write:Unsigned.UInt.of_int uint

  let bool_int = view ~read:((<>) 0) ~write:Bool.to_int int

  module Device = struct
    let t = ptr T.Device.t

    let create = foreign "gbm_create_device" @@ fd @-> returning (ptr_opt T.Device.t)
    let destroy = foreign "gbm_device_destroy" @@ t @-> returning void

    let get_format_modifier_plane_count = foreign "gbm_device_get_format_modifier_plane_count" @@
      t @-> drm_format @-> modifier @-> returning int

    let get_backend_name = foreign "gbm_device_get_backend_name" @@ t @-> returning string
    let is_format_supported = foreign "gbm_device_is_format_supported" @@ t @-> drm_format @-> T.Bo_flags.t @-> returning bool_int
  end

  module Bo = struct
    let t = ptr T.Bo.t

    let create =
      foreign "gbm_bo_create" @@
      ptr T.Device.t @->
      int_uint32_t @->
      int_uint32_t @->
      drm_format @->
      uint32_t @->
      returning (ptr_opt T.Bo.t)

    let create_with_modifiers2 =
      foreign "gbm_bo_create_with_modifiers2" @@
      ptr T.Device.t @->
      int_uint32_t @->
      int_uint32_t @->
      drm_format @-> ptr modifier @-> int_uint @->
      uint32_t @->
      returning (ptr_opt T.Bo.t)

    let destroy = foreign "gbm_bo_destroy" @@ t @-> returning void

    let get_offset = foreign "gbm_bo_get_offset" @@ t @-> int @-> returning int_uint32_t
    let get_stride_for_plane = foreign "gbm_bo_get_stride_for_plane" @@ t @-> int @-> returning int_uint32_t
    let get_fd = foreign "gbm_bo_get_fd" @@ t @-> returning fd
    let get_fd_for_plane = foreign "gbm_bo_get_fd_for_plane" @@ t @-> int @-> returning fd
    let get_plane_count = foreign "gbm_bo_get_plane_count" @@ t @-> returning int
    let get_handle = foreign "gbm_bo_get_handle" @@ t @-> returning T.Bo_handle.t
    let get_handle_for_plane = foreign "gbm_bo_get_handle_for_plane" @@ t @-> int @-> returning T.Bo_handle.t
    let get_modifier = foreign "gbm_bo_get_modifier" @@ t @-> returning modifier
    let get_bpp = foreign "gbm_bo_get_bpp" @@ t @-> returning int_uint32_t

    let get_width = foreign "gbm_bo_get_width" @@ t @-> returning int_uint32_t
    let get_height = foreign "gbm_bo_get_height" @@ t @-> returning int_uint32_t

    type map_data = unit Ctypes.ptr
    let map_data = ptr void

    let map = foreign "gbm_bo_map" @@
      t @->
      int_uint32_t @-> int_uint32_t @->
      int_uint32_t @-> int_uint32_t @->
      uint32_t @-> ptr int_uint32_t @-> ptr map_data @->
      returning (ptr_opt void)

    let unmap = foreign "gbm_bo_unmap" @@ t @-> map_data @-> returning void
  end
end
